name: core
description: A new Flutter package.
version: 0.0.0
homepage: https://github.com/syntaxltd/flutter-clean-architecture
publish_to: none

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^2.3.6+1
  stacked: ^2.3.15
  auto_route: ^3.2.4
  logger: ^1.1.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  adaptive_dialog: ^1.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  auto_route_generator: ^3.2.3
  injectable_generator:

flutter:
