name: domain
description: A new Flutter package.
version: 0.0.0
homepage: https://github.com/Dennis-Mwea/flutter-clean-architecture

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.0
  injectable: ^2.1.1
  freezed: ^2.3.4
  dio: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.2
  injectable_generator: ^2.1.5
  freezed_annotation: ^2.2.0

flutter:
